version: '2.1'

services:
  logs:
    entrypoint:
    - '/bin/logspout'
    - '${LOGSPOUT_ENDPOINT}'
    ports:
    - 5001:80

  elastic:
    environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms7g -Xmx7g"
    ulimits:
      nproc: 3000
      nofile: 65536
      memlock: -1
    mem_limit: 10g

  nginx:
    image: morpheus-nginx
    restart: always
    ports:
    - 443:443

  telegraf:
    build: telegraf
    hostname: morpheus-telegraf
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /var/run/utmp:/var/run/utmp:ro
    environment:
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
      STATS_TOKEN: ${APP_STATS_TOKEN}
      STATS_HOST: ${APP_HOST_NAME}
    pid: host
    restart: always
