version: '3.4'

services:
  logs:
    entrypoint:
    - '/bin/logspout'
    - '${LOGSPOUT_ENDPOINT}'
    ports:
    - 5001:80

  nginx:
    image: morpheus-nginx
    restart: always
    ports:
    - 443:443

# no telegraf
